# Core Setup
# title:           "NoConformity"
# description:     "This is the personal blog of Chris Hough. I write rants, crazy opinions, thoughts on startup life, and everything else in between.  If you have opinions for my opinions reach out to me, but make sure you read my disclaimer first."
# slogan:          "I write lines of code, I mark my body with art, and I have no time for mediocrity. Get on, or get off this party bus, no one rides for free."

# Owner/author information
owner:
  name:           Chris Hough
  author:         Chris Hough
  email:          chris@noconformity.com
  twitter:        chrishough
  instagram:      chrishough
  github:         chrishough
  foursquare:     chrishough


# Startup Data
startup:
  url:       http://lustocracy.com
  url_slogan: "Lustocracy empowers people to own their sexuality by providing a safe, sexy, and authentic community, and by sharing exhilarating and revolutionary experiences. Lustocracy is Modern. American. Sex."
  editorial: http://pov.lustocracy.com
  editorial_slogan: "POV is the official blog of Lustocracy, a technology and media company that facilitates exhilarating and revolutionary sexual expression. Our mission is to empower people to own their sexuality by providing a safe, sexy, and authentic community, and by sharing exhilarating and revolutionary experiences."

# Analytics and Webmaster tools
# google_analytics: UA-37324451-1
# google_analytics_site: noconformity.com

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title/
relative_permalinks: false

# Jekyll Configurations : Include|Exclude Files
destination: _site
plugins: _plugins
archive_dir: "archive"
category_dir: "category"
category_dir_list: "categories"
tag_dir: "tag"
tag_dir_list: "tags"
relative_permalinks: false
include: ["index.html","_pages"]
exclude: [".bundle","Guardfile", "Gemfile", "Gemfile.lock", "README.md", "readme.md", "S3_website.yml", "lib", ".DS_Store", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

# markdown: redcarpet
# redcarpet:
#   extensions: ["quote", "highlight", "no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks"]
#
# # Instagram plugin
# instagram_cache: true
# instagram_cache_dir: '.instagram-cache'
