lsi: true
url: http://noconformity.com
search_url: http://noconformity.com
# Jekyll Assets
assets:
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets
    - _assets/V2/css
    - _assets/V2/css/font
    - _assets/V2/css/font/fontawesome
    - _assets/V2/css/theme
    - _assets/V2/javascript
    - _assets/V2/images
    - _assets/V2/images/projects
    - _assets/V2/images/resume
    - _assets/V2/images/skills
    - _assets/V2/images/theme
    - content
    - content/500x320
    - content/500x500
    - content/placeholder
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
